RPI_SENSOR_DIR = "/var/www/html/sensor"

# commonly used values
TIMESTAMP = "timestamp"
VERSION = "version"
HOST = "host"
SENSORS = "sensors"
CONTROLS = "controls"
NAME = "name"
VALUE = "value"
VALUES = "values"
IP_ADDRESS = "ip_address"
OPERATING_SYSTEM = "operating_system"
UNIT_OF_MEASUREMENT = "unit_of_measurement"
MODULE_NAME = "module_name"
CLASS_NAME = "class_name"
